# Site settings
title: getaclue
email: alex_at_getakluew.com
description: > # this means to ignore newlines until "baseurl:"
  I'm just trying to make the world a better place by using the
  tools that make it possible.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://getaclue.github.io/" # the base hostname & protocol for your site
twitter_username: alexkluew
github_username:  getaclue

# Build settings
markdown: kramdown

# Windows Problem
highlighter: false
